services:
  server:
    image: gitea/gitea:1.22.3
    networks:
      - gitea
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "22:22"

volumes:
  gitea:
    driver: local

networks:
  gitea:
    driver: bridge