version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"  # Porta para acesso à interface do Portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - portainer_network
    environment:
      AGENT_SECRET: my_secret_password

  #agent:
  #  image: portainer/agent:2.21.4
  #  container_name: portainer_agent
  #  restart: always
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #    - /var/lib/docker/volumes:/var/lib/docker/volumes
  #  networks:
  #    - portainer_network
  #  environment:
  #    AGENT_CLUSTER_ADDR: tasks.agent
  #    AGENT_SECRET: my_secret_password

volumes:
  portainer_data:

networks:
  portainer_network:
